name: Molecule

on:
  push:
    branches:
      - main
      - release/v*
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          # - centos-7
          # - debian-9
          # - fedora-28
          # - oraclelinux-7
          # - ubuntu-18.04
        python-version: ["3.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: "${{ github.repository }}"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: show pwd
        run: | 
          pwd
          ls -la
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}