name: Molecule

on:
  push:
    branches:
      - main
      - release/v*
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: true 
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          # - centos-7
          # - debian-9
          # - fedora-28
          # - oraclelinux-7
          # - ubuntu-18.04
        python-version: ["3.10", "3.9", "3.8", "3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: "${{ github.repository }}"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Molecule
        run: |
          molecule --debug test --scenario-name ${{ matrix.scenario }}
      # - name: Molecule
      #   uses: gofrolist/molecule-action@v2
      #   with:
      #     molecule_options: --debug --base-config molecule/_shared/base.yml
      #     molecule_command: test
      #     molecule_args: --scenario-name ${{ matrix.scenario }}